export const FETCH_ARTICLES_STARTED = 'FETCH_ARTICLES_STARTED';
export const FETCH_ARTICLE_SUCCESSED = 'FETCH_ARTICLE_SUCCESSED';
export const FETCH_ARTICLE_FAILED = 'FETCH_ARTICLE_FAILED';
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL';
